agent {
    data_dir          = "/tmp/spire/agent/data"
    log_level         = "DEBUG"
    server_address    = "spire-server"
    server_port       = "8081"
    socket_path       = "/run/spire/sockets/agent.sock"
    trust_bundle_path = "/run/spire/secrets/bundle.crt"
    trust_domain      = "conjur.test"
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "memory" {
        plugin_data {}
    }

    WorkloadAttestor "unix" {
        plugin_data {}
    }
}
